#!/usr/bin/env python3
"""Generate src/purefzf/normalize.py from fzf's src/algo/normalize.go.

Usage: python tools/gen_normalize.py /path/to/fzf/src/algo/normalize.go
"""
import re
import sys
from pathlib import Path

HEADER = '''"""Normalization table for latin script letters, ported from fzf.

Generated by tools/gen_normalize.py from fzf's src/algo/normalize.go.
Do not edit by hand.
"""

NORMALIZED = {
'''

FOOTER = '''}


def normalize_rune(ch):
    """Map a latin script letter with diacritics to its base letter."""
    cp = ord(ch)
    if cp < 0x00C0 or cp > 0xFF61:
        return ch
    return NORMALIZED.get(ch, ch)


def normalize_str(s):
    """Normalize every rune in the string (the equivalent of algo.NormalizeRunes)."""
    return "".join([normalize_rune(ch) for ch in s])
'''


def main():
    src = Path(sys.argv[1]).read_text()
    entries = re.findall(r"0x([0-9A-Fa-f]+):\s*'(\\.|.)'", src)
    if not entries:
        sys.exit("no entries found")
    out = [HEADER]
    for code, base in entries:
        if base.startswith("\\"):
            base = base[1:]
        out.append("    \"\\u%04x\": %r,\n" % (int(code, 16), base))
    out.append(FOOTER)
    dest = Path(__file__).resolve().parent.parent / "src" / "purefzf" / "normalize.py"
    dest.write_text("".join(out))
    print("wrote %s entries to %s" % (len(entries), dest))


if __name__ == "__main__":
    main()
